apiVersion: v2
appVersion: "1.0"
description: A Helm chart for RD Location Ref Data Load App
name: rd-location-ref-data-load
home: https://github.com/hmcts/rd-location-ref-data-load
version: 0.0.5
maintainers:
  - name: Reference Data Team
dependencies:
  - name: job
    version: ~0.6.0
    repository: '@hmctspublic'
