job:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: locrefdata
    POSTGRES_USERNAME: locrefdata
    POSTGRES_PASSWORD: locrefdata
    FLYWAY_ENABLED: true
    CONTAINER_NAME: lrd-ref-data
  keyVaults:
    rd:
      secrets:
        - BLOB-URL-SUFFIX
        - ApplicationInsightsInstrumentationKey
  secrets:
    BLOB_ACCOUNT_NAME:
      secretRef: storage-secret-{{ .Release.Name }}
      key: storageAccountName
    BLOB_ACCESS_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessKey
    BLOB_SERVICE_ENDPOINT:
      secretRef: storage-secret-{{ .Release.Name }}
      key: primaryBlobServiceEndPoint
global:
  jobKind: CronJob

postgresql:
  enabled: true
  image:
    tag: '11.3.0'
  postgresqlUsername: locrefdata
  postgresqlPassword: locrefdata
  postgresqlDatabase: locrefdata
  persistence:
    enabled: false

blobstorage:
  resourceGroup: rd-aks-pr-test
  teamName: "RD"
  location: ukwest
  setup:
    containers:
      - lrd-ref-data
      - lrd-ref-data-archive
  enabled: true
