jdbc-batch-size: 10
routes-to-execute: lrd-ccd-casetype-load
route:
  lrd-ccd-casetype-load:
    id: lrd-ccd-casetype-load
    file-name: Service.csv
    table-name: service_to_ccd_case_type_assoc
    delete-sql:
      sql:delete from service_to_ccd_case_type_assoc where ccd_case_type in (select ccd_case_type
      from service_to_ccd_case_type_assoc where service_code = :#service_code
      and  ccd_case_type <> :#ccd_case_type) and service_code = :#service_code?batch=true&dataSource=dataSource
    insert-sql:
      sql:insert into service_to_ccd_case_type_assoc (service_code, ccd_service_name, ccd_case_type, created_date)
      values (:#service_code,:#ccd_service_name,:#ccd_case_type, now() at time zone 'utc')
      on conflict (service_code, ccd_case_type) do nothing ?batch=true&dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/lrd-ref-data/Service.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: ServiceToCcdServiceProcessor
    mapper-class: ServiceToCcdServiceMapper
    csv-binder-object: ServiceToCcdService
