jdbc-batch-size: 10
routes-to-execute: lrd-ccd-casetype-load, lrd-court-venue-load
route:
  lrd-ccd-casetype-load:
    id: lrd-ccd-casetype-load
    file-name: OrgServiceCCDMapping.csv
    table-name: service_to_ccd_case_type_assoc
    truncate-sql:
      sql:truncate service_to_ccd_case_type_assoc restart identity?dataSource=dataSource
    insert-sql:
      sql:insert into service_to_ccd_case_type_assoc (service_code, ccd_service_name, ccd_case_type, created_date)
      values (:#service_code,:#ccd_service_name,:#ccd_case_type, now() at time zone 'utc')
      on conflict (service_code, ccd_case_type) do nothing ?batch=true&dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/lrd-ref-data/OrgServiceCCDMapping.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: serviceToCcdCaseTypeProcessor
    mapper-class: serviceToCcdCaseTypeMapper
    csv-binder-object: serviceToCcdCaseType

  lrd-court-venue-load:
    id: lrd-court-venue-load
    file-name: CourtVenue.csv
    table-name: court_venue
    insert-sql:
      sql:insert into court_venue (epimms_id, site_name, court_name, court_status, court_open_date, region_id, court_type_id, cluster_id, open_for_public,
      court_address, postcode, phone_number, closed_date, court_location_code, dx_address, welsh_site_name, welsh_court_address, created_time, updated_time)
      values (:#epimms_id, :#site_name, :#court_name, :#court_status, TO_DATE(NULLIF(:#court_open_date,''), 'dd/MM/yyyy'), :#region_id, :#court_type_id,
      :#cluster_id, :#open_for_public::boolean, :#court_address, :#postcode, :#phone_number, TO_DATE(NULLIF(:#closed_date,''), 'dd/MM/yyyy'),
      :#court_location_code, :#dx_address, :#welsh_site_name, :#welsh_court_address, now() at time zone 'utc', now() at time zone 'utc')
      on conflict (court_location_code) do update set epimms_id = :#epimms_id, site_name = :#site_name, court_name = :#court_name, court_status = :#court_status, court_open_date = TO_DATE(NULLIF(:#court_open_date,''), 'dd/MM/yyyy'),
      region_id = :#region_id, court_type_id = :#court_type_id, cluster_id = :#cluster_id, open_for_public = :#open_for_public::boolean, court_address = :#court_address,
      postcode = :#postcode, phone_number = :#phone_number, closed_date = TO_DATE(NULLIF(:#closed_date,''), 'dd/MM/yyyy'),
      dx_address = :#dx_address, welsh_site_name = :#welsh_site_name, welsh_court_address = :#welsh_court_address, updated_time = now() at time zone 'utc'?batch=true&dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/lrd-ref-data/CourtVenue.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: courtVenueProcessor
    mapper-class: courtVenueMapper
    csv-binder-object: courtVenue

