jdbc-batch-size: 10
routes-to-execute: lrd-ccd-casetype-load,lrd-buildinglocation-load
route:
  lrd-ccd-casetype-load:
    id: lrd-ccd-casetype-load
    file-name: OrgServiceCCDMapping.csv
    table-name: service_to_ccd_case_type_assoc
    truncate-sql:
      sql:truncate service_to_ccd_case_type_assoc restart identity?dataSource=dataSource
    insert-sql:
      sql:insert into service_to_ccd_case_type_assoc (service_code, ccd_service_name, ccd_case_type, created_date)
      values (:#service_code,:#ccd_service_name,:#ccd_case_type, now() at time zone 'utc')
      on conflict (service_code, ccd_case_type) do nothing ?batch=true&dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/lrd-ref-data/OrgServiceCCDMapping.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: serviceToCcdCaseTypeProcessor
    mapper-class: serviceToCcdCaseTypeMapper
    csv-binder-object: serviceToCcdCaseType
#Route: lrd-buildinglocation-load
  lrd-buildinglocation-load:
    id: lrd-buildinglocation-load
    file-name: building_location.csv
    table-name: building_location
    insert-sql:
      sql:insert into building_location (epimms_id, building_location_name, building_location_status, area, region_id, cluster_id, court_finder_url, postcode, address, created_time, updated_time)
      values (:#epimms_id,:#building_location_name,:#building_location_status,:#area,:#region_id,:#cluster_id,:#court_finder_url,:#postcode,:#address,now() at time zone 'utc',now() at time zone 'utc')
      on conflict (epimms_id) do update set building_location_name = :#building_location_name,building_location_status = :#building_location_status,area = :#area,region_id = :#region_id,cluster_id = :#cluster_id,court_finder_url = :#court_finder_url,postcode = :#postcode,address = :#address,updated_time = now() at time zone 'utc'?batch=true&dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/lrd-ref-data/building_location.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: buildingLocationProcessor
    mapper-class: buildingLocationMapper
    csv-binder-object: buildingLocation


