java:
  applicationPort: 8099
  image: 'hmctspublic.azurecr.io/rd/fee-pay-ref-data-load:latest'
  ingressHost: rd-fee-pay-ref-data-load-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: rd
  environment:
  keyVaults:
    rd:
      secrets:
        - AppInsightsInstrumentationKey
        - rd-fee-pay-ref-data-load-s2s-secret
